from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path


_ID_RE = re.compile(r"^[a-zA-Z0-9_]+\.[a-zA-Z0-9_]+$")


def validate_template_id(value: str) -> str:
    v = (value or "").strip()
    if not _ID_RE.match(v):
        raise ValueError("template_id must look like 'namespace.Name' (letters/numbers/underscore + dot)")
    return v


@dataclass(frozen=True)
class AugustusTemplateSpec:
    template_id: str
    name: str
    author: str
    description: str
    goal: str
    detector: str
    severity: str
    tags: list[str]
    prompts: list[str]


def render_template_yaml(spec: AugustusTemplateSpec) -> str:
    # Matches augustus pkg/templates/types.go structure.
    # Keep it simple and ASCII; user prompts are YAML strings.
    tags = [t for t in spec.tags if t]
    if tags:
        tags_yaml = "  tags:\n" + "\n".join(f"    - {t!r}" for t in tags)
    else:
        tags_yaml = "  tags: []"

    prompts_yaml = "\n".join(f"  - {p!r}" for p in spec.prompts if p)
    if not prompts_yaml:
        prompts_yaml = "  - ''"

    now = datetime.utcnow().isoformat(timespec="seconds") + "Z"

    return (
        f"# Generated by suite_web at {now}\n"
        f"id: {spec.template_id!r}\n"
        "info:\n"
        f"  name: {spec.name!r}\n"
        f"  author: {spec.author!r}\n"
        f"  description: {spec.description!r}\n"
        f"  goal: {spec.goal!r}\n"
        f"  detector: {spec.detector!r}\n"
        f"{tags_yaml}\n"
        f"  severity: {spec.severity!r}\n"
        "prompts:\n"
        f"{prompts_yaml}\n"
    )


def write_template_file(target_dir: Path, filename_base: str, spec: AugustusTemplateSpec) -> Path:
    target_dir.mkdir(parents=True, exist_ok=True)
    path = target_dir / f"{filename_base}.yaml"
    path.write_text(render_template_yaml(spec), encoding="utf-8")
    return path

