from __future__ import annotations

import importlib.util
import re
import sys
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path


_SAFE_NAME_RE = re.compile(r"^[a-zA-Z_][a-zA-Z0-9_]{0,63}$")

# Garak expects probes under garak.probes.*; we put custom probes in
# <custom_probes_dir>/<user_id>/garak/probes/<module>.py and shim garak/__init__.py
# and garak/probes/__init__.py so that with this dir first on PYTHONPATH,
# "import garak.probes.<module>" loads our file.

_GARAK_SHIM_INIT = '''# Shim so custom probes are loadable as garak.probes.<module>
# This dir must be first on PYTHONPATH when running garak.
import importlib.util
import sys
from pathlib import Path

_root = Path(__file__).resolve().parent.parent
_path = str(_root)
_self = sys.modules["garak"]
_sys_path_before = list(sys.path)
sys.path = [p for p in sys.path if Path(p).resolve() != _root]
_removed = len(sys.path) < len(_sys_path_before)
del sys.modules["garak"]
import garak as _real_garak
_real_probes = importlib.import_module("garak.probes")
if _removed:
    sys.path.insert(0, _path)
sys.modules["garak"] = _self

# Merge real garak.probes with our custom probe .py files
_probes_dir = Path(__file__).resolve().parent / "probes"
_merged = type(sys)("garak.probes")
_merged.__dict__.update({k: v for k, v in _real_probes.__dict__.items() if not k.startswith("_")})
sys.modules["garak.probes"] = _merged
globals()["probes"] = _merged
for f in sorted(_probes_dir.glob("*.py")):
    if f.stem.startswith("_") or f.name == "__init__.py":
        continue
    mod_name = f.stem
    spec = importlib.util.spec_from_file_location("garak.probes." + mod_name, f)
    if spec is None or spec.loader is None:
        continue
    mod = importlib.util.module_from_spec(spec)
    sys.modules["garak.probes." + mod_name] = mod
    spec.loader.exec_module(mod)
    _merged.__dict__[mod_name] = mod

_d = {k: v for k, v in _real_garak.__dict__.items()}
_d["probes"] = _merged
globals().update(_d)

# Register custom probe classes in garak's plugin cache so CLI accepts them
try:
    _plugins_mod = __import__("garak._plugins", fromlist=["PluginCache"])
    _cache = _plugins_mod.PluginCache.instance()
    for _mod_name, _mod in list(_merged.__dict__.items()):
        if not isinstance(_mod, type(sys)) or not getattr(_mod, "__file__", ""):
            continue
        if str(Path(_mod.__file__).resolve()).startswith(str(_probes_dir.resolve())):
            for _attr in dir(_mod):
                if _attr.startswith("_"):
                    continue
                _klass = getattr(_mod, _attr, None)
                if isinstance(_klass, type) and issubclass(_klass, _real_probes.Probe):
                    _key = f"probes.{_mod_name}.{_attr}"
                    if _key not in _cache.get("probes", {}):
                        try:
                            _cache.setdefault("probes", {})[_key] = _plugins_mod.PluginCache.plugin_info(_klass)
                        except Exception:
                            pass
except Exception:
    pass
'''

_GARAK_PROBES_SHIM_INIT = '''# Placeholder so this package exists; merge is done in garak/__init__.py
'''


def safe_module_name(name: str) -> str:
    """
    Convert arbitrary user titles into a safe python module name.
    """
    base = re.sub(r"[^a-zA-Z0-9_]+", "_", (name or "").strip().lower()).strip("_")
    if not base:
        base = "custom_probe"
    if not re.match(r"^[a-zA-Z_]", base):
        base = "_" + base
    base = base[:64]
    if not _SAFE_NAME_RE.match(base):
        base = "custom_probe"
    return base


@dataclass(frozen=True)
class PromptOnlyProbeSpec:
    module_name: str
    class_name: str
    title: str
    doc_uri: str
    goal: str
    tags: list[str]
    primary_detector: str
    active: bool
    prompts: list[str]


def render_probe_module(spec: PromptOnlyProbeSpec) -> str:
    # Keep generated code simple; it will run server-side.
    tags_list = "[" + ", ".join(repr(t) for t in spec.tags if t) + "]"
    prompts_list = "[" + ", ".join(repr(p) for p in spec.prompts if p) + "]"
    now = datetime.utcnow().isoformat(timespec="seconds") + "Z"

    return (
        '"""**Custom (prompt-only) garak probe**\n\n'
        "Generated by suite_web.\n"
        f"Generated at: {now}\n"
        '"""\n\n'
        "import garak.probes\n\n\n"
        f"class {spec.class_name}(garak.probes.Probe):\n"
        f'    """{spec.title}\n\n'
        "    Prompt-only custom probe generated from the web UI.\n"
        '    """\n\n'
        f"    doc_uri = {spec.doc_uri!r}\n"
        f"    active = {bool(spec.active)}\n"
        f"    tags = {tags_list}\n"
        f"    goal = {spec.goal!r}\n"
        f"    primary_detector = {spec.primary_detector!r}\n"
        f"    prompts = {prompts_list}\n"
        "\n"
    )


def ensure_garak_probes_shims(target_dir: Path) -> None:
    """Create garak/__init__.py and garak/probes/__init__.py so custom probes are loadable as garak.probes.<module>."""
    garak_dir = target_dir / "garak"
    probes_dir = garak_dir / "probes"
    probes_dir.mkdir(parents=True, exist_ok=True)

    # Migrate legacy flat probes: if target_dir has *.py, move into garak/probes/
    for f in target_dir.glob("*.py"):
        if f.name.startswith("_"):
            continue
        dest = probes_dir / f.name
        if not dest.exists():
            dest.write_text(f.read_text(), encoding="utf-8")
            f.unlink()

    garak_init = garak_dir / "__init__.py"
    garak_init.write_text(_GARAK_SHIM_INIT, encoding="utf-8")
    probes_init = probes_dir / "__init__.py"
    probes_init.write_text(_GARAK_PROBES_SHIM_INIT, encoding="utf-8")


def write_probe_module(target_dir: Path, spec: PromptOnlyProbeSpec) -> Path:
    ensure_garak_probes_shims(target_dir)
    probes_dir = target_dir / "garak" / "probes"
    path = probes_dir / f"{spec.module_name}.py"
    path.write_text(render_probe_module(spec), encoding="utf-8")
    return path


def probe_module_path(target_dir: Path, module_name: str) -> Path:
    """Path to a probe module file (garak/probes/<module_name>.py under target_dir)."""
    return target_dir / "garak" / "probes" / f"{module_name}.py"


def run_uses_custom_probes(custom_dir: Path, probes_param: str | list) -> bool:
    """True if probes_param includes at least one custom probe for this user (custom_dir)."""
    if not custom_dir.exists():
        return False
    probes_dir = custom_dir / "garak" / "probes"
    if not probes_dir.exists():
        return False
    if isinstance(probes_param, list):
        clauses = [str(p).strip() for p in probes_param if str(p).strip()]
    else:
        clauses = [s.strip() for s in str(probes_param or "").split(",") if s.strip()]
    for clause in clauses:
        if "." in clause:
            module_name = clause.split(".", 1)[0]
            if (probes_dir / f"{module_name}.py").exists():
                return True
    return False


def validate_class_name(name: str) -> str:
    n = (name or "").strip()
    if not n:
        return "CustomProbe"
    n = re.sub(r"[^a-zA-Z0-9_]+", "_", n)
    if not re.match(r"^[a-zA-Z_]", n):
        n = "CustomProbe"
    n = n[:64]
    return n
